=== HODAMOHAMED1/JavaFX_Chatapp/Javafx_Chat_client/build/classes/XML/message.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
<xs:element name="Message" type="message"/>
 <xs:complexType name="message">
        <xs:sequence>
            <xs:element name="Mymessage" type="MymessageType" maxOccurs="unbounded" />    
        </xs:sequence>
         <xs:attribute name="owner" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="MymessageType">
        <xs:sequence>
            <xs:element name="from" type="xs:string"/>
            <xs:element name="to" type="xs:string" maxOccurs="unbounded"/>
            <xs:element name="color" type="xs:string"/>
            <xs:element name="size" type="fontSize"/>
            <xs:element name="family" type="fontFamily"/>
            <xs:element name="body" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="fontSize">
        <xs:restriction base="xs:positiveInteger">
            <xs:minExclusive value="8"/>
            <xs:maxExclusive value="24"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="fontFamily">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Arial"/>
            <xs:enumeration value="Times New Roman"/>
            <xs:enumeration value="Courier New"/>
            <xs:enumeration value="Fleftex"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== HODAMOHAMED1/JavaFX_Chatapp/Javafx_Chat_client/output.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><?xml-stylesheet type='text/xsl' href='message.xsl'?>
<Message xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="message.xsd">
    <Mymessage>
        <from>ahmed22</from>
        <color>green</color>
        <size>10</size>
        <family>Fleftex</family>
        <body> .nfasdajs</body>
    </Mymessage>
    <Mymessage>
        <from>ahmed22</from>
        <color>green</color>
        <size>10</size>
        <family>Fleftex</family>
        <body>adnbs</body>
    </Mymessage>
</Message>

=== HODAMOHAMED1/JavaFX_Chatapp/Javafx_Chat_client/build/classes/XML/output.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><?xml-stylesheet type='text/xsl' href='message.xsl'?>
<Message xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="message.xsd">
    <Mymessage>
        <from>Hoda</from>
        <color>green</color>
        <size>10</size>
        <family>Fleftex</family>
        <body>hjkkjnd</body>
    </Mymessage>
    <Mymessage>
        <from>Ahmed.hesham</from>
        <color>green</color>
        <size>28</size>
        <family>Arial</family>
        <body>izayk ya hoda </body>
    </Mymessage>
    <Mymessage>
        <from>Hoda</from>
        <color>blue</color>
        <size>22</size>
        <family>Courier New</family>
        <body>ezyak ya a7md</body>
    </Mymessage>
    <Mymessage>
        <from>Ahmed.hesham</from>
        <color>black</color>
        <size>28</size>
        <family>Arial</family>
        <body>2na elhamdlelah bslm il project </body>
    </Mymessage>
</Message>

=== HODAMOHAMED1/JavaFX_Chatapp/Javafx_Chat_client/build/classes/XML/message.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?xml-stylesheet type="text/xsl" href="message.xsl"?>

<Message
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='message.xsd' owner="hoda">
    <Mymessage>
        <from>hoda</from>
        <to>ahmed</to>
        <color>Red</color>
        <size>10</size>
        <family>Arial</family>
        <body>hello</body>
    </Mymessage>
    <Mymessage>
        <from>ahmed</from>
        <to>hoda</to>
        <color>green</color>
        <size>12</size>
        <family>Arial</family>
        <body>hiiii</body>
    </Mymessage>
    <Mymessage>
        <from>hoda</from>
        <to>ahmed</to>
        <color>yellow</color>
        <size>9</size>
        <family>Times New Roman</family>
        <body>welcome</body>
    </Mymessage>

</Message>
